"""add meal_type and date

Revision ID: 672874dd96d6
Revises: 
Create Date: 2026-06-06 17:20:09.442356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672874dd96d6'
down_revision = 'e3a4f5b6c7d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('meal_type')

    # ### end Alembic commands ###
