"""Add grams column to meal

Revision ID: b3593567f1bd
Revises: 60fdb4f50239
Create Date: 2026-10-04 16:02:15.435056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3593567f1bd'
down_revision = '60fdb4f50239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grams', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_column('grams')

    # ### end Alembic commands ###
