"""add saved_food table

Revision ID: c6089ab7fb50
Revises: b3593567f1bd
Create Date: 2026-10-05 14:23:18.967101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6089ab7fb50'
down_revision = 'b3593567f1bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food', sa.String(length=100), nullable=False),
    sa.Column('verdict', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('swap', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_food')
    # ### end Alembic commands ###
